language: node_js
node_js: 0.1
notifications:
  email: false
services: PostgreSQL
env:
  DATABASE_URL: postgres://postgres:@127.0.0.1/egress_test
before_script:
- sudo apt-get install python-software-properties=0.82.7.5 -m
- sudo add-apt-repository ppa:chris-lea/node.js -y
- npm install zombie
- npm ls
- psql -c 'create database egress_test;' -U postgres
- psql -f databases/users.sql -U postgres -d egress_test
deploy:
  provider: heroku
  api_key:
    secure: AohSB4/UJqbmKcYVmpap8Ryp14HlhVAEvPSU41/TVzA26EE1xTVXEL9BnebX3ChUrdb8dnmIh2eFfcccgMCROjgm55JRZY2dh5Z1rQ4o4BKcWMyVNMJVkvfIaIYCXREb9gNdmjWm8O6jMlNAGjVzWtGLGGMdsdEtrp5F3gWoYHQ=
  app:
    master: egress-bootstrap
    develop: egress-bootstrap-dev
